#include<stdio.h>
#include<stdlib.h>
#include<math.h>
#include<string.h>

struct node_data
{
 double xn,yn,zn;
};
struct node_data *node;

struct cell_data
{
 int number_of_nodes,node[15],celltype;
};
struct cell_data *cell;

struct face_data
{
    int node[3],cell[3],bc;
};
struct face_data *face, *face_temp;

int main()
{
    char dummy[100];
    FILE *fp;
    fp = fopen("uniformGrid.vtk","r");
    int n,c,f;

    fscanf(fp,"%s %s %s %s %s",dummy, dummy, dummy, dummy, dummy);
    fscanf(fp,"%s %s %s %s",dummy, dummy, dummy, dummy);
    fscanf(fp,"%s",dummy);
    fscanf(fp,"%s %s",dummy, dummy);
    fscanf(fp,"%s %d %s",dummy, &n, dummy);

    node = (struct node_data *) malloc((n+1)*sizeof(struct node_data));

    for (int i=1;i<=n;i++)
        fscanf(fp,"%lf %lf %lf",&node[i].xn,&node[i].yn,&node[i].zn);

    fscanf(fp,"%s %d %s",dummy, &c, dummy);

    cell = (struct cell_data *) malloc((c+1)*sizeof(struct cell_data));

    for (int i=1;i<=c;i++)
    { 
        fscanf(fp,"%d",&cell[i].number_of_nodes);
        for (int j=1;j<=cell[i].number_of_nodes;j++)
            fscanf(fp,"%d",&cell[i].node[j]);
    }

    fscanf(fp,"%s %s",dummy, dummy);

    for (int i=1;i<=c;i++)
        fscanf(fp,"%d",&cell[i].celltype);

    fclose(fp);

    FILE *pf;

    pf = fopen("vtktest.vtk","w");

    fprintf(pf,"# vtk DataFile Version 3.0\n");
    fprintf(pf,"VTK datafile generated by Trushant\n");
    fprintf(pf,"ASCII\n");
    fprintf(pf,"DATASET UNSTRUCTURED_GRID\n");
    fprintf(pf,"POINTS %d double\n",n);

    for(int i=1;i<=n;i++)
        fprintf(pf,"%24.16E\t%24.16E\t%24.16E\n",node[i].xn,node[i].yn,node[i].zn);

    fprintf(pf,"CELLS %d %d\n",c,c*4);

    for (int i=1;i<=c;i++)
    {
        fprintf(pf,"%d\t",cell[i].number_of_nodes);
        for (int j=1;j<=cell[i].number_of_nodes;j++)
        {
            fprintf(pf,"%d\t",cell[i].node[j]);
        }
        fprintf(pf,"\n");
    }

    fprintf(pf,"CELL_TYPES %d\n",c);

    for(int i=1;i<=c;i++)
        fprintf(pf,"5\n");	

    fclose(pf);

    FILE *tkp;

    tkp = fopen("unstructured.grid","w");

    fprintf(tkp,"%d\n",n);

    for(int i=1;i<=n;i++)
        fprintf(tkp,"%24.16E\t%24.16E\t%24.16E\n",node[i].xn,node[i].yn,node[i].zn);

    fprintf(tkp,"%d\n",c);

    for (int i=1;i<=c;i++)
    {
        fprintf(tkp,"%d\t",cell[i].number_of_nodes);
        for (int j=1;j<=cell[i].number_of_nodes;j++)
        {
            fprintf(tkp,"%d\t",cell[i].node[j]+1);
        }
        fprintf(tkp,"\n");
    }

    face_temp = (struct face_data *) malloc((c+1)*3*sizeof(struct face_data));
    f = 0;
    int node1, node2;
    int flag;

    for (int i=1;i<=c;i++)
    {
        for (int j=1;j<=cell[i].number_of_nodes;j++)
        {
            if (j != cell[i].number_of_nodes)
            {
                node1 = cell[i].node[j];
                node2 = cell[i].node[j+1];
            }
            else
            {
                node1 = cell[i].node[j];
                node2 = cell[i].node[1];
            }
            flag = 0;
            for (int k=1;k<=f+1;k++)
            {
               if ((node1 == face_temp[k].node[1] && node2 == face_temp[k].node[2]) || (node1 == face_temp[k].node[2] && node2 == face_temp[k].node[1]))
               {
                    flag = 1;
                    face_temp[k].cell[1] = i;
                    break;
               }
            //    else
            //    {
            //        face_temp[k].cell[2] = -1;
            //    }
               
            }
            if (flag == 0)
            {
                f++;
                face_temp[f].node[1] = node1;
                face_temp[f].node[2] = node2;
                face_temp[f].cell[2] = i;
                // printf("%d\t%d\n",face_temp[f].cell[1],face_temp[f].cell[2]);
            }
        }
    }

    fprintf(tkp,"%d\n",f);

    for (int k=1;k<=f;k++)
    {
        fprintf(tkp,"%d\t%d\t%d\t%d\t",face_temp[k].node[1]+1,face_temp[k].node[2]+1,face_temp[k].cell[1],face_temp[k].cell[2]);
        if (node[face_temp[k].node[1]+1].xn == 0.0 && node[face_temp[k].node[2]+1].xn == 0.0)
        {
            fprintf(tkp,"1001\n");
        }
        else if (node[face_temp[k].node[1]+1].xn == 1.0 && node[face_temp[k].node[2]+1].xn == 1.0)
        {
            fprintf(tkp,"1003\n");
        }
        else if (node[face_temp[k].node[1]+1].yn == 0.0 && node[face_temp[k].node[2]+1].yn == 0.0)
        {
            fprintf(tkp,"1002\n");
        }
        else if (node[face_temp[k].node[1]+1].yn == 1.0 && node[face_temp[k].node[2]+1].yn == 1.0)
        {
            fprintf(tkp,"1004\n");
        }
        else
        {
            fprintf(tkp,"0\n");
        }
        
    }

    fclose(tkp);

    return 0;
}