#include "global.h"

int writingVTK()
{

  printf("*****WRITING OUTPUT FILE IN .vtk FORMAT*****\n");

  // File pointer
  FILE *fp;
  // Array for storing the temperature at each node
  double T_p[n];
  double dist, t_dist;

  // Creating a vtk file for writing the output
  fp = fopen("poisson_general.vtk", "w");

  // Initial syntax for legacy VTK file
  fprintf(fp, "# vtk DataFile Version 3.0\n");
  fprintf(fp, "VTK datafile generated by Trushant\n");
  fprintf(fp, "ASCII\n");
  fprintf(fp, "DATASET UNSTRUCTURED_GRID\n");
  // Total number of nodes
  fprintf(fp, "POINTS %d double\n", n);

  // Writing the node data by looping over all the nodes
  for (i = 1; i <= n; i++)
  {
    fprintf(fp, "%24.16E\t%24.16E\t%24.16E\n", node[i].xn, node[i].yn, node[i].zn);
  }

  // Total number of cells
  fprintf(fp, "CELLS %d %d\n", c, count);

  // Writing the cell data by looping over all the cells
  for (i = 1; i <= c; i++)
  {
    fprintf(fp, "%d\t", cell[i].num_nodes);
    for (j = 1; j <= cell[i].num_nodes; j++)
    {
      fprintf(fp, "%d\t", cell[i].node[j] - 1);
    }
    fprintf(fp, "\n");
  }

  // Cell types
  fprintf(fp, "CELL_TYPES %d\n", c);

  // Writing the cell types
  for (i = 1; i <= c; i++)
  {
    if (ncell[i].num_of_faces == 4)
      fprintf(fp, "9\n");
    if (ncell[i].num_of_faces == 3)
      fprintf(fp, "5\n");
  }

  // Writing the temperature data for each cell
  fprintf(fp, "CELL_DATA %d\n", c);
  fprintf(fp, "SCALARS Processor_Number int\n");
  fprintf(fp, "LOOKUP_TABLE default\n");

  for (i = 1; i <= c; i++)
  {
    fprintf(fp, "%d\n", procID[i]);
  }

  // Writing the temperature data for each node
  fprintf(fp, "POINT_DATA %d\n", n);
  fprintf(fp, "SCALARS Temperature double\n");
  fprintf(fp, "LOOKUP_TABLE default\n");

  for (i = 1; i <= n; i++)
  {
    T_p[i] = 0.0;
    t_dist = 0.0;
    for (j = 1; j <= n2c[i].num_of_cells; j++)
    {
      dist = pow((xc[n2c[i].cell[j]] - node[i].xn), 2) + pow((yc[n2c[i].cell[j]] - node[i].yn), 2);
      dist = pow(dist, 0.5);
      t_dist = t_dist + dist;
      T_p[i] = T_p[i] + dist * Told[n2c[i].cell[j]];
    }
    T_p[i] = T_p[i] / t_dist;
    fprintf(fp, "%24.16E\n", T_p[i]);
  }

  // Closing the VTK output file
  fclose(fp);

  printf("*****OUTPUT FILE IN .vtk FORMAT WRITTEN*****\n\n");

  return (0);
}